# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://git.corp.conviva.com/device/conviva-ios-podspecrepo.git'
target 'DemoApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DemoApp
pod 'ConvivaAVFoundation','3.0.0.1963'

end
